### ISSUE TITLE
[dicom archive, Img browser] page freezes(?) while downloading

### ISSUE THREAD

**Issue by christinerogers** [aces/loris-demo-project#30]
Happening on both the Dicom Archive and the Imaging Browser - Dicom download links : 

I've clicked a download - the tar is downloading. 
No other links work on the page while this is in progress (e.g. View details) 
Using chrome. 

Not sure if it's a release bug or because the .tars aren't yet in place on Demo.

**Comment by cmadjar** [comment]
Can't reproduce this error but we found another issue which have been logged in redmine:
https://redmine.cbrain.mcgill.ca/issues/16494

**Comment by cmadjar** [comment]
FYI - redmine issue with memory problem has been fixed

**Comment by christinerogers** [comment]
This is still happening (in a way):  I can rollover links and use filters while the download is still (attempting to) download --- but clicking on "View Details" or "View Images" does nothing.
@ridz1208  @cmadjar
